#!/bin/bash

# get phone's battery

battery=$(cat /sys/class/power_supply/BAT1/capacity 2>/dev/null)
charge=$( cat /sys/class/power_supply/BAT1/status 2>/dev/null)

if [[ "$battery" =~ ^-?[[:digit:]]+$ ]]; then
	if [[ "$charge" == "Charging" ]]; then
		icon=""

		if [[ "$battery" -gt 99 ]]; then
			echo "ﮤ Unplug"
		else
			echo "$icon $battery%"
		fi
	else
		if [[ "$battery" -gt 85 ]]; then
			icon=""
		elif [[ "$battery" -gt 60 ]]; then
			icon=""
		elif [[ "$battery" -gt 35 ]]; then
			icon=""
		elif [[ "$battery" -gt 10 ]]; then
			icon=""
		else
			icon=""
		fi

		echo "$icon $battery%"
	fi
else
	echo " NA"
fi
